/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import database.MyConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

public class RegisterForm extends javax.swing.JFrame {

    Connection con;
    public RegisterForm() {
        initComponents();
        this.setLocationRelativeTo(null);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfJobdesk = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dateSigndate = new com.toedter.calendar.JDateChooser();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(230, 126, 34));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("-");
        jLabel1.setToolTipText("");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel1);
        jLabel1.setBounds(333, 15, 12, 34);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setToolTipText("");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2);
        jLabel2.setBounds(363, 0, 19, 64);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Register");
        jLabel3.setToolTipText("");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(33, 3, 120, 58);

        jPanel4.add(jPanel3);
        jPanel3.setBounds(0, 0, 400, 70);

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 220));
        jPanel2.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(232, 232, 232));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(220, 220, 221));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Click here to login.");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel4);
        jLabel4.setBounds(60, 270, 300, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setText("Jobdesk");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 70, 70, 17);

        tfJobdesk.setBackground(new java.awt.Color(127, 140, 141));
        tfJobdesk.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(tfJobdesk);
        tfJobdesk.setBounds(150, 70, 170, 20);

        pfPassword.setBackground(new java.awt.Color(127, 140, 141));
        pfPassword.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(pfPassword);
        pfPassword.setBounds(150, 130, 170, 20);

        btnSubmit.setBackground(new java.awt.Color(51, 102, 255));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel2.add(btnSubmit);
        btnSubmit.setBounds(220, 220, 90, 30);

        btnCancel.setBackground(new java.awt.Color(231, 76, 60));
        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel);
        btnCancel.setBounds(110, 220, 80, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setText("Sign Date");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(60, 160, 70, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 240, 241));
        jLabel7.setText("Username");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(60, 100, 70, 17);

        tfUsername.setBackground(new java.awt.Color(127, 140, 141));
        tfUsername.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(tfUsername);
        tfUsername.setBounds(150, 100, 170, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 240, 241));
        jLabel8.setText("Name");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(60, 40, 70, 17);

        tfName.setBackground(new java.awt.Color(127, 140, 141));
        tfName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(tfName);
        tfName.setBounds(150, 40, 170, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(236, 240, 241));
        jLabel9.setText("Password");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(60, 130, 70, 17);

        dateSigndate.setBackground(new java.awt.Color(127, 140, 141));
        dateSigndate.setForeground(new java.awt.Color(127, 140, 141));
        jPanel2.add(dateSigndate);
        dateSigndate.setBounds(150, 160, 170, 20);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(0, 70, 400, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if (tfName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please add a name.");
        } else if (tfJobdesk.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please add a jobdesk.");
        } else if (tfUsername.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please add a username");
        } else if (String.valueOf(pfPassword.getPassword()).equals("")){
            JOptionPane.showMessageDialog(null, "Please add a password");
        } else if (dateSigndate.getDate() == null){
            JOptionPane.showMessageDialog(null, "Please select the sign date");
        } else {
        try {
            con = MyConnection.getMyConnection();
            String query = "INSERT INTO login VALUES (?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, tfName.getText());
            ps.setString(2, tfJobdesk.getText());
            ps.setString(3, tfUsername.getText());
            ps.setString(4, String.valueOf(pfPassword.getPassword()));
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            String sDate = formatter.format(dateSigndate.getDate());
            ps.setString(5, sDate);
            if(ps.executeUpdate() > 0){
                JOptionPane.showMessageDialog(null, tfUsername.getText() + " Berhasil ditambahkan.");
                btnCancel.doClick();
            } else {
                JOptionPane.showMessageDialog(null, tfUsername.getText() + " Gagal diregistrasi.");
            }
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSubmitActionPerformed
    }
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        tfName.setText("");
        tfJobdesk.setText("");
        tfUsername.setText("");
        pfPassword.setText("");
        dateSigndate.setDate(null);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private com.toedter.calendar.JDateChooser dateSigndate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfJobdesk;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
